os: linux

deploy:
  provider: s3
  access_key_id: AKIAS3HIP2PXVPVKNRM7
  secret_access_key:
    secure: "K6VeNGoqkyg0HLJQaxraMz5QypqI2vj9RYT7t6OUjNMcGWcEtyB9Ab91hbPf1ZksZ957Uaxs6jyfCV8eLwQDl9YgLeRMWYtvuaWY1lVnA5zMoGhd5b65KQFMlu6Xa5VADf/Ag3OVJBbxo9juC55XUebydu3jxnoSc8kKOTftACjGCXrbf1bjOkSuv5ggS0rhtCZMPLQDNxJYyXXGtTa0x5XXiu+5iRyooVX0xBmD/Lbwd4+5+RDGe2CUWeH/R/UCSs+rk+hWoCGkrRNc4zEX1FjpWkbUgGIOC5MNHYMrKrTIkI1XinltxtJ6GPJPmcprn+Xgf0YF8kjZBFZ94RpLkaQVp72eavrYQcZvzb7Zi8yPAo5m9FDffrv2BKHE90ifbjssOZrVKNli+CHSa+Qy2/EGTBzpi5cZtbdFyrPflGpn9Zk50isFqkF5Oxdvfv6aVujxfgUFhDjZ/jAphZzCmjfgvOeqyxzOIC7r6alLQJuvPgFlykqIbrHy0p0Q8SGHB88z+SuN04ittpE/efhdrQc2IUpnN0XnVOmT7iUSxRFXcpdrQFKwe7OoRTUZ/Z5Y9+kxC4+Q3YBoNGF8s4Xq21UenJu4Dsw3eMD1YiTO02xYw9EvRYQ98QAhmfxXzP6m01L5uerZ+oMZssHVZl6gzBDhZpESHL6sUgO2SMQvfh4="
  bucket: servo-builds2
  acl: public_read
  region: us-west-2
  on:
    branch: master
  condition: $TRAVIS_PULL_REQUEST = "false"
