name: Deploy

on:
  push:
    branches: ["master", "auto"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_result:
    name: homu build finished
    runs-on: ubuntu-latest
    steps:
      - name: Mark the job as successful
        run: exit 0
        if: success()
      - name: Mark the job as unsuccessful
        run: exit 1
        if: "!success()"
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Deploy static site to S3 bucket
        # bucket name: `servo-builds2`
        run: aws s3 sync . s3://servo-builds2 --acl=public-read --exclude=.git
